version: '3.5'

services:
    apache_php:
        build: .docker/apache_php
        container_name: apache_php
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html

    db:
        image: library/mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: roselle
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db
            MYSQL_PASSWORD: db
        ports:
            - 3306:3306
        volumes:
            - .docker/data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 8080
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80
        depends_on:
            - db

    maildev:
        image: maildev/maildev
        container_name: maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8090:80

    dockerize:
        image: jwilder/dockerize
        container_name: dockerize

    blackfire:
        image: blackfire/blackfire:2
        container_name: blackfire
        ports: ['8307']
        environment:
            BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
            BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
            BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
            BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_DISABLE_LEGACY_PORT: 1
